services:
  pick-and-place-machine:
    build:
      context: ./machine_test_double
      dockerfile: Dockerfile
    container_name: pick-and-place-machine
    depends_on:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto:1.6.14
    container_name: ie-databus
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
